### ISSUE TITLE
JSON output rewrites resulted file which cause missing report

### ISSUE THREAD

**Issue by noskovao** [nvuillam/npm-groovy-lint#185]
When using "**-o /tmp/lint/report/lintResults.json**", the result file getting overwritten with the last checked file.
```
[config] /tmp/lint/.mega-linter.yml + Environment variables
----------------------------------------------------------------------------------------------------
------------------------------------------- Mega-Linter --------------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2021-10-07T03:32:53Z
 - Image Revision: db564312
 - Image Version: latest
----------------------------------------------------------------------------------------------------
The Mega-Linter documentation can be found at:
 - https://nvuillam.github.io/mega-linter
----------------------------------------------------------------------------------------------------
GITHUB_REPOSITORY:
GITHUB_REF:
GITHUB_RUN_ID:


[Activation] EDITORCONFIG_EDITORCONFIG_CHECKER has been set inactive, as none of these files has been found: ['.editorconfig']
[Activation] JAVASCRIPT_ES has been set inactive, as none of these files has been found: ['.eslintrc.json', '.eslintrc.yml', '.eslintrc.yaml', '.eslintrc.js', '.eslintrc.cjs']
[Activation] JSX_ESLINT has been set inactive, as none of these files has been found: ['.eslintrc.json', '.eslintrc.yml', '.eslintrc.yaml', '.eslintrc.js', '.eslintrc.cjs']
[Activation] SWIFT_SWIFTLINT has been set inactive, as none of these files has been found: ['.swiftlint.yml']
[Activation] TSX_ESLINT has been set inactive, as none of these files has been found: ['.eslintrc.json', '.eslintrc.yml', '.eslintrc.yaml', '.eslintrc.js', '.eslintrc.cjs']
[Activation] TYPESCRIPT_ES has been set inactive, as none of these files has been found: ['.eslintrc.json', '.eslintrc.yml', '.eslintrc.yaml', '.eslintrc.js', '.eslintrc.cjs']
Skipped linters: ANSIBLE_ANSIBLE_LINT, EDITORCONFIG_EDITORCONFIG_CHECKER, JAVASCRIPT_ES, JAVASCRIPT_PRETTIER, JSX_ESLINT, KUBERNETES_KUBEVAL, MARKDOWN_REMARK_LINT, SALESFORCE_SFDX_SCANNER_APEX, SALESFORCE_SFDX_SCANNER_AURA, SALESFORCE_SFDX_SCANNER_LWC, SWIFT_SWIFTLINT, TSX_ESLINT, TYPESCRIPT_ES, TYPESCRIPT_PRETTIER
To receive reports as email, please set variable EMAIL_REPORTER_EMAIL
Listing updated files in [/tmp/lint] using git diff.
Modified files:
utils/certificate-check/Jenkinsfile
utils/certificate-check/seed.groovy
- File extensions: , .R, .RMD, .Rmd, .bash, .c, .c++, .cc, .cdxml, .clj, .cljc, .cljs, .coffee, .cpp, .cs, .css, .cu, .cuh, .cxx, .dart, .dash, .edn, .env, .feature, .go, .gradle, .graphql, .groovy, .gvy, .h, .h++, .hcl, .hh, .hpp, .htm, .html, .hxx, .java, .js, .json, .json5, .jsonc, .ksh, .kt, .kts, .lua, .md, .nf, .p6, .php, .pl, .pl6, .pm, .pm6, .pp, .proto, .ps1, .ps1xml, .psd1, .psm1, .psrc, .pssc, .py, .r, .raku, .rakumod, .rakutest, .rb, .rs, .rst, .saas, .scala, .scss, .sh, .smk, .sql, .t, .tex, .tf, .ts, .vb, .xml, .yaml, .yml
- File names (regex): Dockerfile, Jenkinsfile, Snakefile
Kept [2] files on [2] found files

+----MATCHING LINTERS-----------+--------------------------------------+----------------+------------+
| Descriptor  | Linter          | Criteria                             | Matching files | Format/Fix |
+-------------+-----------------+--------------------------------------+----------------+------------+
| COPYPASTE   | jscpd           |                                      | project        | no         |
| CREDENTIALS | secretlint      |                                      | project        | no         |
| GIT         | git_diff        |                                      | project        | no         |
| GROOVY      | npm-groovy-lint | .groovy|.gvy|.gradle|.nf|Jenkinsfile | 2              | no         |
| SPELL       | misspell        |                                      | 2              | no         |
| SPELL       | cspell          |                                      | 2              | no         |
+-------------+-----------------+--------------------------------------+----------------+------------+

Mega-Linter flavor [ci_light] does not contain linters COPYPASTE_JSCPD,CREDENTIALS_SECRETLINT,SPELL_MISSPELL,SPELL_CSPELL.
As they are not available in this docker image, they will not be processed
To solve this problem, please either:
- use default flavor nvuillam/mega-linter
- add ignored linters in DISABLE or DISABLE_LINTERS variables in your .mega-linter.yml config file located in your root directory
- ignore this message by setting config variable FLAVOR_SUGGESTIONS to false

### Processed [GIT] files
- Using [git_diff v2.30.2] https://git-scm.com
- Mega-Linter key: [GIT_GIT_DIFF]
- Rules config: identified by [git_diff]
✅ Linted [GIT] files with [git_diff] successfully - (2.19s)
[Text Reporter] Generated TEXT report: /tmp/lint/report/linters_logs/SUCCESS-GIT_GIT_DIFF.log

### Processed [GROOVY] files
- Using [npm-groovy-lint v9.0.0] https://nvuillam.github.io/npm-groovy-lint/
- Mega-Linter key: [GROOVY_NPM_GROOVY_LINT]
- Rules config: [/.groovylintrc.json]
[npm-groovy-lint] utils/certificate-check/Jenkinsfile - ERROR - 1 error(s)
--Error detail:
GroovyLint: Logged results in file /tmp/lint/report/lintResults.json
Failure: 0 error(s) have been found
 8 warning(s) have been found

[npm-groovy-lint] utils/certificate-check/seed.groovy - ERROR - 1 error(s)
--Error detail:
GroovyLint: Logged results in file /tmp/lint/report/lintResults.json
Failure: 0 error(s) have been found
 5 warning(s) have been found

❌ Linted [GROOVY] files with [npm-groovy-lint]: Found 2 error(s) - (6.72s)
[Text Reporter] Generated TEXT report: /tmp/lint/report/linters_logs/ERROR-GROOVY_NPM_GROOVY_LINT.log
```

As you can see we have two lines with: "**GroovyLint: Logged results in file /tmp/lint/report/lintResults.json**"
with a context of /seed.groovy report, so Jenkinsfile is missed.

**Comment by nvuillam** [comment]
The call to npm-groovy-lint contains instruction to output in a named JSON file, so it's normal that for 2 calls, the second one overrides the first

Please can you try with `GROOVY_NPM_GROOVY_LINT_CLI_LINT_MODE: project` in mega-linter config file ?

**Comment by noskovao** [comment]
With `GROOVY_NPM_GROOVY_LINT_CLI_LINT_MODE: project ` I'm getting the following error:
```
docker run --rm --name megalinter \
-e GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
-e PRINT_ALPACA=false -e VALIDATE_ALL_CODEBASE=false \
-e DEFAULT_BRANCH=main -v /Users/alex/work/git/nc-cicd:/tmp/lint \
-v ~/.ssh_megalinter:/root/.ssh nvuillam/mega-linter-ci_light@sha256:3c147d4711e75ee75ba45900244adf709f7078b61401c928cf3f2ad168ccecb3

...
...

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/megalinter/MegaLinter.py", line 27, in run_linters
    linter.run()
  File "/megalinter/Linter.py", line 504, in run
    return_code, stdout = self.process_linter()
  File "/megalinter/Linter.py", line 614, in process_linter
    command = self.build_lint_command(file)
  File "/megalinter/linters/GroovyNpmGroovyLintLinter.py", line 16, in build_lint_command
    dir_name = os.path.dirname(file)
  File "/usr/local/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
"""
```
Here is my config:
```
cat .mega-linter.yml
cat .mega-linter.yml
---
GROOVY_NPM_GROOVY_LINT_ARGUMENTS: "--failon warning -o '/tmp/lint/report/myLintResults.html'"
GROOVY_NPM_GROOVY_LINT_CLI_LINT_MODE: "project"
FILTER_REGEX_EXCLUDE: (src/|vars/)
```

I've also tried with `list_of_files` which I believe exactly what I need to just changed files, but getting the following error:
```
[Activation] EDITORCONFIG_EDITORCONFIG_CHECKER has been set inactive, as none of these files has been found: ['.editorconfig']
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/megalinter/run.py", line 9, in <module>
    linter = megalinter.Megalinter({"cli": True})
  File "/megalinter/MegaLinter.py", line 96, in __init__
    self.load_linters()
  File "/megalinter/MegaLinter.py", line 344, in load_linters
    all_linters = linter_factory.list_all_linters(linter_init_params)
  File "/megalinter/linter_factory.py", line 30, in list_all_linters
    descriptor_linters = build_descriptor_linters(
  File "/megalinter/linter_factory.py", line 92, in build_descriptor_linters
    linter_instance = linter_class(linter_init_params, instance_attributes)
  File "/megalinter/Linter.py", line 223, in __init__
    self.load_config_vars()
  File "/megalinter/Linter.py", line 418, in load_config_vars
    raise KeyError(
KeyError: 'You can not override {self.name} cli_lint_mode with list_of_files, as it can process files only one by one. If you think it could be done, post an issue :)'
```

**Comment by noskovao** [comment]
@nvuillam do you have any other ideas for the above topic?
