### ISSUE TITLE
Exception when linting Interface class

### ISSUE THREAD

**Issue by andywow** [nvuillam/npm-groovy-lint#230]
I declared empty interface

```
package mypackage.security

interface SecurityCheck {
}

```

and got exception, when sending request to codenarc server

stack:
```
Error: Request failed with status code 500
    at createError (/Users/xxx/.nvm/versions/node/v16.13.1/lib/node_modules/npm-groovy-lint/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/xxx/.nvm/versions/node/v16.13.1/lib/node_modules/npm-groovy-lint/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/xxx/.nvm/versions/node/v16.13.1/lib/node_modules/npm-groovy-lint/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
```

Exception:
```
org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
com.nvuillam.CodeNarcServer.parseFile(CodeNarcServer.groovy:273)
jdk.internal.reflect.GeneratedMethodAccessor831.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
com.nvuillam.CodeNarcServer$_parseFiles_closure6.doCall(CodeNarcServer.groovy:249)
jdk.internal.reflect.GeneratedMethodAccessor830.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
groovy.lang.Closure.call(Closure.java:412)
groovy.lang.Closure.call(Closure.java:428)
org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2358)
org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2343)
org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2384)
org.codehaus.groovy.runtime.dgm$202.invoke(Unknown Source)
org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
com.nvuillam.CodeNarcServer.parseFiles(CodeNarcServer.groovy:248)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
com.nvuillam.CodeNarcServer$_initialize_closure3.doCall(CodeNarcServer.groovy:128)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
groovy.lang.Closure.call(Closure.java:412)
org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:110)
com.sun.proxy.$Proxy9.handle(Unknown Source)
jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:730)
jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:699)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)"
```

when i run `npm-groovy-lint` with `--noserver` arg, i don`t have same error

**Comment by nvuillam** [comment]
I am currently preparing to launch npm-groovy-lint v10, I solve and issue which looks similar, let's hope it will solve this one :)
You can star/follow the repo to see the release :) ( soon )

**Comment by andywow** [comment]
Thank you, will wait for new release ) 
Want to say that same Exception i have if i declare class without default constructor with no arguments

**Comment by nvuillam** [comment]
@andywow should be ok with latest version, please can you confirm ? Thanks :)

![image](https://user-images.githubusercontent.com/17500430/184503662-44417795-0e22-4191-9984-c6a7fab99c93.png)

**Comment by andywow** [comment]
@nvuillam, yes, now it's work! Thanks a lot!

**Comment by nvuillam** [comment]
@andywow great, I m glad your case works :)
