### ISSUE TITLE
crash when return void from void method

### ISSUE THREAD

**Issue by lexdene** [nvuillam/npm-groovy-lint#289]
code:

    class Sample {

      void foo() {
        print('foo')
      }

      void bar() {
        return foo()
      }

    }

run command:

    docker run --rm -u "$(id -u):$(id -g)" -w=/tmp -v "$PWD":/tmp nvuillam/npm-groovy-lint:latest

got error:

    CodeNarcServer unexpected error:
    {
      "message": "Request failed with status code 500",
      "name": "Error",
      "stack": "Error: Request failed with status code 500\n    at createError (/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:326:22)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
      "config": {
        "url": "http://localhost:7484/request",
        "method": "post",

**Comment by lexdene** [comment]
the error data is too long to post onto github issue.
