### ISSUE TITLE
SyntaxError: Unexpected token ;

### ISSUE THREAD

**Issue by phts** [nvuillam/npm-groovy-lint#93]
Tried latest version as well as version 2.2.0 which requires Node.js 8+.

```
$ npm-groovy-lint               
/usr/local/lib/node_modules/npm-groovy-lint/jdeploy-bundle/groovy-lint.js:16
    "use strict";
                ^

SyntaxError: Unexpected token ;
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

Points to https://github.com/nvuillam/npm-groovy-lint/blob/v2.2.0/src/groovy-lint.js#L16 (2.2.0) and https://github.com/nvuillam/npm-groovy-lint/blob/master/lib/groovy-lint.js#L18 on latest version.

Node.js: 10.14.2
npm: 6.15.5
OS: Macos 10.15.6

**Comment by nvuillam** [comment]
As explained in the documentation, Node 12 minimum is required (javascript class properties declaration are used, and they are not available with Node 10)

https://github.com/nvuillam/npm-groovy-lint#installation
